"""Write web/assets/manifest.js from the packed sprite strips."""
import json
from PIL import Image

A = "web/assets"
FRAME = 224
ANCHOR_X, ANCHOR_Y = 95, 220

# name: (fps or duration, loop, hitAt) — hitAt is the fraction of the clip where the strike lands
ANIMS = {
    "idle": dict(fps=8, loop=True),
    "walk": dict(fps=12, loop=True),
    "jump": dict(fps=12, loop=False),
    # 5-hit combo, 4 frames each (wind-up, swing, swing, strike) = 20 frames.
    # Frames play over the first `playFor` of the clip, then the strike frame holds.
    # hitAt lands on the frame where the stick crosses in front of Kan.
    "attack1": dict(duration=0.30, playFor=0.7, hitAt=0.7 * 0.75),
    "attack2": dict(duration=0.30, playFor=0.7, hitAt=0.7 * 0.5),
    "attack3": dict(duration=0.36, playFor=0.7, hitAt=0.7 * 0.75),
    "attack4": dict(duration=0.36, playFor=0.7, hitAt=0.7 * 0.5),
    "attack5": dict(duration=0.50, playFor=0.7, hitAt=0.7 * 0.75),
}

anims = {}
for name, cfg in ANIMS.items():
    src = f"assets/kan_{name}.png"
    strip = Image.open(f"web/{src}")
    n = strip.width // FRAME
    a = {"image": src, "frames": n, "frameW": FRAME, "frameH": FRAME,
         "anchorX": ANCHOR_X, "anchorY": ANCHOR_Y, "loop": cfg.get("loop", False)}
    a.update({k: v for k, v in cfg.items() if k != "loop"})
    if "duration" not in a:
        a["duration"] = n / a["fps"]
    if name == "jump":
        # the clip moves the body inside the frame; pin each frame by its feet instead
        a["bottoms"] = [strip.crop((i * FRAME, 0, (i + 1) * FRAME, FRAME)).getbbox()[3] for i in range(n)]
    anims[name] = a

manifest = {
    "worldWidth": 2600,
    "groundY": 318,
    "background": "assets/bg_village.png",
    "portrait": "assets/kan_portrait.png",
    "portraitCrop": {"x": 92, "y": 50, "w": 120, "h": 120},
    "player": {"scale": 0.62, "anims": anims, "reach": [96, 90, 104, 98, 118]},
    "monster": {"image": "assets/monster_yak.png", "anchorX": 84, "anchorY": 160, "scale": 0.85,
                "artFacing": 1, "hp": 320, "speed": 46, "hitHeight": 115, "barHeight": 150},
}
with open(f"{A}/manifest.js", "w") as f:
    f.write("// Generated by tools/build_manifest.py\nwindow.MANIFEST = " + json.dumps(manifest, indent=1) + ";\n")
print("ok", {k: v["frames"] for k, v in anims.items()})
