"""Write web/assets/manifest.js: the stage and the shared skill effects.

Fighters are not in here: each one lives in web/characters/<id>/character.js.
"""
import json
import os

A = "web/assets"
VFX = ["bird", "naga", "chakra", "tiger", "rocks", "yama", "storm",
       "crack", "fists", "blades", "buffalo", "groundfire", "guard",
       "magnet", "ramasun", "wind", "sunfire", "icespear", "blink", "blinkrift",
       "claw", "clawheavy", "clawx", "tigerclaw", "tigerbeast", "jungleaura", "leaves", "bullet", "pistol",
       "goldbolt", "goldburst", "bluebolt", "goldbeam", "fireblast", "thunderball", "whirl", "rocket", "talai", "rocketride", "bigride", "taphotwave", "spiritwave", "bloodslash", "spiritshield", "spiritguard", "whiteimpact", "bloodring"]
# animated effect sheets from tools/fetch_vfx.py: key -> (fps, loop)
VFX_ANIM = {"bird": (16, True), "naga": (18, True), "tiger": (18, True),
            "rocks": (0, False), "yama": (0, False), "storm": (16, True),
            "buffalo": (18, True), "groundfire": (14, True), "fists": (24, True),
            "magnet": (16, True), "ramasun": (0, False), "sunfire": (12, True),
            "tigerbeast": (14, True), "jungleaura": (12, True)}

vfx_anim = {}
for key, (fps, loop) in VFX_ANIM.items():
    meta = f"web/assets/vfx_{key}_anim.json"
    if os.path.exists(meta):
        info = json.load(open(meta))
        vfx_anim[key] = {"image": f"assets/vfx_{key}_anim.png", "fps": fps, "loop": loop, **info}

manifest = {
    "worldWidth": 2600,
    "groundY": 306,
    "background": "assets/bg_village.png",
    "vfx": {k: f"assets/vfx_{k}.png" for k in VFX},
    "vfxAnim": vfx_anim,
}
with open(f"{A}/manifest.js", "w") as f:
    f.write("// Generated by tools/build_manifest.py\nwindow.MANIFEST = " + json.dumps(manifest, indent=1) + ";\n")
print("ok", sorted(manifest))
